name: 'slackbot-file-uploader'
description: 'A bot that will post a message and/or upload a file to slack'

inputs:
  slack-bot-user-oauth-access-token:
    description: 'Oauth Token'
    required: true

  slack-channel:
    description: 'Slack channel to post to'
    required: true

  slack-file:
    description: 'File to upload'
    required: false

  slack-message:
    description: 'Message to send with file'
    required: true


outputs:
  message:
    description: 'Message that was posted'

runs:
  using: 'node12'
  main: 'dist/index.js'
