name: 'slackbot-bot-automation'
description: 'A bot that will post a message and/or upload a file to slack'

inputs:
  slack-bot-user-oauth-access-token:
    description: 'Oauth Token'
    required: true

  slack-bot-function:
    description: 'Function you want the bot to use'
    required: false

  slack-channel:
    description: 'Slack channel to post to'
    required: true

  slack-file:
    description: 'File to upload'
    required: false

  slack-message-header:
    description: 'Message to send: header, used with conjuction of body (If there is content), header will always print'
    required: false

  slack-message-body:
    description: 'Message to send: If body is empty, nothing will print'
    required: false

  slack_optional_input_link_names:
    description: 'Find and link channel names and usernames.'
    required: false

  slack_optional_input_username:
    description: Set your bot's user name. Must be used in conjunction with as_user set to false, otherwise ignored.
    required: false

  slack_optional_input_as_user:
    description: Pass true to post the message as the authed user, instead of as a bot. Defaults to false.
    required: false

outputs:
  message:
    description: 'If the message sent was a success or not'

runs:
  using: 'node12'
  main: 'dist/index.js'
